#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
package ESxSNMP::Constants;
require 5.6.0;
use strict;
use warnings;
use Thrift;


use constant ESDBErrors => [
'unknown device',
'unknown oidset',
'unknown var',
'unknown consolidation function',
'resolution unavailable',
];

1;
