#!/usr/bin/env python

"""
esmond-ps-get - client to fetch perfsonar test results.
"""

import os
import socket
import sys

from esmond_client.perfsonar.query import ApiConnect
from esmond_client.perfsonar.util import (perfsonar_client_opts, 
    perfsonar_client_filters, output_factory, data_format_factory) 

def main():
    options, args = perfsonar_client_opts(require_src_dest=True,
        require_event=True)

    filters = perfsonar_client_filters(options)
    conn = ApiConnect(options.url, filters)

    header, data = data_format_factory(options)(conn)

    o = output_factory(options, data, header)
    print o.get_output()

    pass

if __name__ == '__main__':
    main()