#!/usr/bin/env python

import threading
from calendar import timegm

from thrift.transport import TSocket, TTransport
from thrift.protocol import TBinaryProtocol
from thrift.server import TServer

import tsdb

from essnmp.sql import *
from essnmp.rpc import ESDB
from essnmp.ipaclsocket import IPACLSocket
import essnmp.rpc.ttypes
from essnmp.poll import remove_metachars

class ESDBHandler(object):
    def __init__(self):
        essnmp.sql.setup_db("postgres:///essnmp")
        self.session = create_session(essnmp.sql.vars['db'])
        self.tsdb = tsdb.TSDB("/data/essnmp/tsdb")
        self.device_threads = {}

    def list_devices(self, active):
        limit = ""
        if active:
            limit = "device.end_time > 'NOW' AND device.begin_time < 'NOW'"

        return [d.name for d in self.session.query(Device).select(limit)]

    def get_device(self,name):
        return self.session.query(Device).select_by(name=name)[0]

    def get_all_devices(self, active):
        d = {}
        for device in self.list_devices(active):
            d[device] = self.get_device(device)

        return d

    def add_device(self, device):
        self.session.save(device)
        self.session.flush()

    def list_oids(self):
        return [o.name for o in self.session.query(OID).select()]

    def get_oid(self,name):
        return self.session.query(OID).select_by(name=name)[0]

    def list_oidsets(self):
        return [s.name for s in self.session.query(OIDSet).select()]

    def get_oidset(self,name):
        return self.session.query(OIDSet).select_by(name=name)[0]

    def select(self, device, iface_name, oidset, oid, begin_time, end_time,
            flags, cf, resolution):
        """
        Returns raw data.

        If resolution is None, return the native resolution of the variable.
        """

        if cf != "AVERAGE":
            raise essnmp.rpc.ttypes.ESDBError(
                    dict(what="unsupported consolidation function: %s" % cf))

        iface_name = remove_metachars(iface_name)

        var = self.tsdb.get_var("/".join((device, oidset, oid, iface_name)))
        data = var.select(int(begin_time), int(end_time))

        l = []

        for datum in data:
            l.append(datum)

        result = essnmp.rpc.ttypes.VarList()

        if isinstance(l[0], essnmp.rpc.ttypes.Counter32):
            result.counter32 = l
        elif isinstance(l[0], essnmp.rpc.ttypes.Counter64):
            result.counter64 = l
        elif isinstance(l[0], essnmp.rpc.ttypes.Gauge32):
            result.gauge32 = l
        else:
            raise essnmp.rpc.ttypes.ESDBError(
                    dict(what="unknown return type from TSDB select"))

        return result

    def get_active_devices(self):
        return self.session.query(Device).select("end_time > 'NOW' and begin_time < 'NOW'")

    def get_interfaces(self, device, all_interfaces):
        """
        Return a list of the most recent IfRef entry for each interface on
        each active device.
        """
        # XXX might be faster to do a join, but need to read up on SQLAlchemy
        # to do that...

        d = self.session.query(Device).select_by(name=device)[0]
        q = """ifref.deviceid = %d
                AND ifref.end_time > 'NOW'
                AND ifref.begin_time < 'NOW'""" % d.id

        if not all_interfaces:
            q += """ AND ifref.ifalias ~* 'show:'"""
        print q

        l = self.session.query(IfRef).select(q)
#        import pdb
#        pdb.set_trace()
        print len(l)
        return l

#
# Make tsdb types Thrifty
#
tsdb.Counter32.__bases__ += (essnmp.rpc.ttypes.Counter32, )
tsdb.Counter64.__bases__ += (essnmp.rpc.ttypes.Counter64, )
tsdb.Gauge32.__bases__ += (essnmp.rpc.ttypes.Gauge32, )

handler = ESDBHandler()
processor = ESDB.Processor(handler)
transport = IPACLSocket(9090, []) #TSocket.TServerSocket(9090)
tfactory = TTransport.TBufferedTransportFactory()
pfactory = TBinaryProtocol.TBinaryProtocolFactory()

server = TServer.TThreadedServer(processor, transport, tfactory, pfactory)

server.serve()
