#!/usr/bin/env python

import sys
import optparse
import traceback

from essnmp.poll import PollManager
from essnmp.util import daemonize, setup_exc_handler, setproctitle
from essnmp.config import get_opt_parser, get_config, get_config_path
from essnmp.error import ConfigError


def main(argv):
    oparse = get_opt_parser(default_config_file=get_config_path())
    (opts, args) = oparse.parse_args(args=argv)

    try:
        config = get_config(opts.config_file, opts)
    except ConfigError, e:
        print e
        sys.exit(1)

    name = "espolld_manager_quux"

    exc_handler = setup_exc_handler(name, config)
    exc_handler.install()

    setproctitle(name)

    daemonize(name, config.pid_file)

    poller = PollManager(name, opts, args, config)
    poller.start_polling()

if __name__ == "__main__":
    main(sys.argv)

