#!/usr/bin/env python

"""
esmond-get - client to fetch perfsonar test results.
"""

import os
import sys

from esmond_client.perfsonar.query import ApiConnect
from esmond_client.perfsonar.util import (perfsonar_client_opts, 
    perfsonar_client_filters, output_factory)

def main():
    options, args = perfsonar_client_opts(require_src_dest=True)

    filters = perfsonar_client_filters(options)
    conn = ApiConnect(options.url, filters)

    data = list()

    for m in conn.get_metadata():
        pass

    pass

if __name__ == '__main__':
    main()