#!/bin/bash

if [ -d /usr/lib/esmond ]; then
    # setup environment on CentOS
    cd /usr/lib/esmond

    if [ -f /opt/rh/python27/enable ]; then
        # setup python 2.7 on CentOS 6
        source /opt/rh/python27/enable
        /opt/rh/python27/root/usr/bin/virtualenv --prompt="(esmond)" .
    fi

    source bin/activate

    if [ -f /etc/profile.d/esmond.sh ]; then
        source /etc/profile.d/esmond.sh
    fi
elif [ -d /usr/lib/python2.7/dist-packages/esmond ]; then
    # setup environment on Debian
    cd /usr/lib/python2.7/dist-packages

    if [ -f /etc/default/esmond ]; then
        source /etc/default/esmond
        export ESMOND_ROOT
        export ESMOND_CONF
        export DJANGO_SETTINGS_MODULE=esmond.settings
    fi
fi

python esmond/manage.py "$@"
