#!/bin/bash

if [ -d /usr/lib/esmond ]; then
    # setup environment on CentOS
    cd /usr/lib/esmond

    source bin/activate

    if [ -f /etc/profile.d/esmond.sh ]; then
        source /etc/profile.d/esmond.sh
    fi
elif [ -d /usr/lib/python3.5/dist-packages/esmond ]; then
    # setup environment on Debian
    cd /usr/lib/python3.5/dist-packages

    if [ -f /etc/default/esmond ]; then
        source /etc/default/esmond
        export ESMOND_ROOT
        export ESMOND_CONF
        export DJANGO_SETTINGS_MODULE=esmond.settings
    fi
fi

python3 esmond/manage.py "$@"
