#!/usr/bin/env python

"""
Small example/test script to post some data to locally running rest 
interface and cassandra instance.
"""

import json
import os
import requests
import sys
import time

from esmond.api.post_data import PostRawData

def main():

    ts = int(time.time()) * 1000

    payload = [
        { 'ts': ts-90000, 'val': 1000 },
        { 'ts': ts-60000, 'val': 2000 },
        { 'ts': ts-30000, 'val': 3000 },
        { 'ts': ts, 'val': 4000 },
    ]

    path = ['rtr_test_post', 'FastPollHC', 'ifHCInOctets', 'interface_test']

    p = PostRawData(port=8000, path=path, freq=30000)
    p.set_payload(payload)
    p.add_to_payload({'ts': ts+1000, 'val': 5000})
    p.send_data()
    # Second call will generate a warning since the first will
    # clear the internal payload.
    p.send_data()

    # Read the data back out.

    url = 'http://localhost:8000/v1/timeseries/RawData/rtr_test_post/FastPollHC/ifHCInOctets/interface_test/30000'

    params = {
        'begin': ts-90000, 'end': ts+1000
    }

    r = requests.get(url, params=params)
    data = json.loads(r.content)

    print json.dumps(data, indent=4)
    pass

if __name__ == '__main__':
    main()