#!/usr/bin/env python

import calendar
import datetime
import json
import os
import pprint
import requests
import sys
import time
import warnings

from optparse import OptionParser

from esmond.api.fetch_data import ApiConnect, ApiFilters

def main():
    import os.path
    from optparse import OptionParser
    usage = '%prog [ -v | -H hostname ]'
    parser = OptionParser(usage=usage)
    parser.add_option('-H', '--hostname', metavar='HOST',
            type='string', dest='hostname', 
            help='Host running rest api (default=%default).', 
            default='localhost')
    parser.add_option('-l', '--last', metavar='LAST',
            type='int', dest='last', default=0,
            help='Last n minutes of data to query.')
    parser.add_option('-d', '--device',
            type='string', action='append', metavar='DEVICE',
            default=[], dest='devices',
            help='Device name to filter (can be more than one use of this flag).')
    parser.add_option('-v', '--verbose',
                dest='verbose', action='count', default=False,
                help='Verbose output - -v, -vv, etc.')
    options, args = parser.parse_args()

    filters = ApiFilters()

    if options.last:
        filters.begin_time = int(time.time() - (options.last*60))

    if options.devices:
        filters.devices = options.devices

    # e = datetime.datetime(year=2013, month=7, day=10)
    # s = e - datetime.timedelta(days=7)
    # print s, e
    # filters.begin_time = s
    # filters.end_time = e

    conn = ApiConnect(options.hostname, filters)

    # return 1

    for d in conn.get_devices():
        print d
        # print d.dump
        print '  *', d.begin_time, '|', d.end_time
        # continue
        for i in d.get_interfaces():
            print '  ', i, i.begin_time
            for e in i.get_endpoints():
                print '   *', e
                print '     +', e.get_data().dump
        break    
    pass

if __name__ == '__main__':
    main()