#!/bin/bash

#set esmond env variables
export ESMOND_ROOT=/usr/lib/esmond
export ESMOND_CONF=/etc/esmond/esmond.conf
export DJANGO_SETTINGS_MODULE=esmond.settings

cd $ESMOND_ROOT

#update DB tables if doing an upgrade
if [ "$1" = "2" ]; then
    python3 esmond/manage.py migrate --fake-initial &> /var/log/esmond/install.log
    #this is just for 3.4.X upgrades only. Makes sure authtoken is created
    python3 esmond/manage.py migrate authtoken &>> /var/log/esmond/install.log
    python3 util/migrate_tastypie_keys.py &>> /var/log/esmond/install.log
fi

#deploy static files
mkdir -p ${ESMOND_ROOT}/staticfiles
django-admin collectstatic --clear --noinput &>> /var/log/esmond/install.log
