/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "esxsnmp_constants.h"

namespace ESxSNMP {

const esxsnmpConstants g_esxsnmp_constants;

esxsnmpConstants::esxsnmpConstants() {
}

} // namespace

