/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef esxsnmp_CONSTANTS_H
#define esxsnmp_CONSTANTS_H

#include "esxsnmp_types.h"

namespace ESxSNMP {

class esxsnmpConstants {
 public:
  esxsnmpConstants();

};

extern const esxsnmpConstants g_esxsnmp_constants;

} // namespace

#endif
