/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef esxsnmp_TYPES_H
#define esxsnmp_TYPES_H

#include <Thrift.h>
#include <reflection_limited_types.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace ESxSNMP {

enum Grouping {
  Commercial = 1,
  Internal = 2,
  ResearchEducation = 3,
  Education = 4,
  Site = 5
};

class OIDType {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  OIDType() : id(0), name("") {
  }

  virtual ~OIDType() throw() {}

  int32_t id;
  std::string name;

  struct __isset {
    __isset() : id(false), name(false) {}
    bool id;
    bool name;
  } __isset;

  bool operator == (const OIDType & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const OIDType &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OIDType & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class OIDCorrelator {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  OIDCorrelator() : id(0), name("") {
  }

  virtual ~OIDCorrelator() throw() {}

  int32_t id;
  std::string name;

  struct __isset {
    __isset() : id(false), name(false) {}
    bool id;
    bool name;
  } __isset;

  bool operator == (const OIDCorrelator & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const OIDCorrelator &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OIDCorrelator & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class OID {
 public:

  static const char* ascii_fingerprint; // = "138DB496E40E0B48699CCC3A9616CC1B";
  static const uint8_t binary_fingerprint[16]; // = {0x13,0x8D,0xB4,0x96,0xE4,0x0E,0x0B,0x48,0x69,0x9C,0xCC,0x3A,0x96,0x16,0xCC,0x1B};

  OID() : id(0), name(""), oidtypeid(0) {
  }

  virtual ~OID() throw() {}

  int32_t id;
  std::string name;
  int32_t oidtypeid;

  struct __isset {
    __isset() : id(false), name(false), oidtypeid(false) {}
    bool id;
    bool name;
    bool oidtypeid;
  } __isset;

  bool operator == (const OID & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(oidtypeid == rhs.oidtypeid))
      return false;
    return true;
  }
  bool operator != (const OID &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OID & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Poller {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  Poller() : id(0), name("") {
  }

  virtual ~Poller() throw() {}

  int32_t id;
  std::string name;

  struct __isset {
    __isset() : id(false), name(false) {}
    bool id;
    bool name;
  } __isset;

  bool operator == (const Poller & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const Poller &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Poller & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class OIDSet {
 public:

  static const char* ascii_fingerprint; // = "03B09FCBDDCCEB482CC7EAD8FD750E1C";
  static const uint8_t binary_fingerprint[16]; // = {0x03,0xB0,0x9F,0xCB,0xDD,0xCC,0xEB,0x48,0x2C,0xC7,0xEA,0xD8,0xFD,0x75,0x0E,0x1C};

  OIDSet() : id(0), name(""), frequency(0), pollerid(0) {
  }

  virtual ~OIDSet() throw() {}

  int32_t id;
  std::string name;
  int32_t frequency;
  std::vector<OID>  oids;
  int32_t pollerid;

  struct __isset {
    __isset() : id(false), name(false), frequency(false), oids(false), pollerid(false) {}
    bool id;
    bool name;
    bool frequency;
    bool oids;
    bool pollerid;
  } __isset;

  bool operator == (const OIDSet & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(frequency == rhs.frequency))
      return false;
    if (!(oids == rhs.oids))
      return false;
    if (!(pollerid == rhs.pollerid))
      return false;
    return true;
  }
  bool operator != (const OIDSet &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OIDSet & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class DeviceTag {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  DeviceTag() : id(0), name("") {
  }

  virtual ~DeviceTag() throw() {}

  int32_t id;
  std::string name;

  struct __isset {
    __isset() : id(false), name(false) {}
    bool id;
    bool name;
  } __isset;

  bool operator == (const DeviceTag & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const DeviceTag &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DeviceTag & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Device {
 public:

  static const char* ascii_fingerprint; // = "1EEFF6E8B2BB859638228DDE65B25E24";
  static const uint8_t binary_fingerprint[16]; // = {0x1E,0xEF,0xF6,0xE8,0xB2,0xBB,0x85,0x96,0x38,0x22,0x8D,0xDE,0x65,0xB2,0x5E,0x24};

  Device() : id(0), name(""), begin_time(0), end_time(0), community("") {
  }

  virtual ~Device() throw() {}

  int32_t id;
  std::string name;
  int64_t begin_time;
  int64_t end_time;
  std::string community;
  std::vector<OIDSet>  oidsets;

  struct __isset {
    __isset() : id(false), name(false), begin_time(false), end_time(false), community(false), oidsets(false) {}
    bool id;
    bool name;
    bool begin_time;
    bool end_time;
    bool community;
    bool oidsets;
  } __isset;

  bool operator == (const Device & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(begin_time == rhs.begin_time))
      return false;
    if (!(end_time == rhs.end_time))
      return false;
    if (!(community == rhs.community))
      return false;
    if (!(oidsets == rhs.oidsets))
      return false;
    return true;
  }
  bool operator != (const Device &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Device & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class IfRef {
 public:

  static const char* ascii_fingerprint; // = "80A5E19654494934B0DDEFDA40A2F5AE";
  static const uint8_t binary_fingerprint[16]; // = {0x80,0xA5,0xE1,0x96,0x54,0x49,0x49,0x34,0xB0,0xDD,0xEF,0xDA,0x40,0xA2,0xF5,0xAE};

  IfRef() : id(0), ifindex(0), ifdescr(""), ifalias(""), ipaddr(""), ifspeed(0), ifhighspeed(0), connection(""), conntype(""), usage(""), visibility(""), grouping("") {
  }

  virtual ~IfRef() throw() {}

  int32_t id;
  Device device;
  int32_t ifindex;
  std::string ifdescr;
  std::string ifalias;
  std::string ipaddr;
  int64_t ifspeed;
  int64_t ifhighspeed;
  std::string connection;
  std::string conntype;
  std::string usage;
  std::string visibility;
  std::string grouping;

  struct __isset {
    __isset() : id(false), device(false), ifindex(false), ifdescr(false), ifalias(false), ipaddr(false), ifspeed(false), ifhighspeed(false), connection(false), conntype(false), usage(false), visibility(false), grouping(false) {}
    bool id;
    bool device;
    bool ifindex;
    bool ifdescr;
    bool ifalias;
    bool ipaddr;
    bool ifspeed;
    bool ifhighspeed;
    bool connection;
    bool conntype;
    bool usage;
    bool visibility;
    bool grouping;
  } __isset;

  bool operator == (const IfRef & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(device == rhs.device))
      return false;
    if (!(ifindex == rhs.ifindex))
      return false;
    if (!(ifdescr == rhs.ifdescr))
      return false;
    if (!(ifalias == rhs.ifalias))
      return false;
    if (!(ipaddr == rhs.ipaddr))
      return false;
    if (!(ifspeed == rhs.ifspeed))
      return false;
    if (!(ifhighspeed == rhs.ifhighspeed))
      return false;
    if (!(connection == rhs.connection))
      return false;
    if (!(conntype == rhs.conntype))
      return false;
    if (!(usage == rhs.usage))
      return false;
    if (!(visibility == rhs.visibility))
      return false;
    if (!(grouping == rhs.grouping))
      return false;
    return true;
  }
  bool operator != (const IfRef &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const IfRef & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Counter32 {
 public:

  static const char* ascii_fingerprint; // = "1584BE3F33D288DCC74EA52051285D05";
  static const uint8_t binary_fingerprint[16]; // = {0x15,0x84,0xBE,0x3F,0x33,0xD2,0x88,0xDC,0xC7,0x4E,0xA5,0x20,0x51,0x28,0x5D,0x05};

  Counter32() : flags(0), timestamp(0), value(0), version(1), type_id(1) {
  }

  virtual ~Counter32() throw() {}

  int32_t flags;
  int32_t timestamp;
  int32_t value;
  int8_t version;
  int8_t type_id;

  struct __isset {
    __isset() : flags(false), timestamp(false), value(false), version(false), type_id(false) {}
    bool flags;
    bool timestamp;
    bool value;
    bool version;
    bool type_id;
  } __isset;

  bool operator == (const Counter32 & rhs) const
  {
    if (!(flags == rhs.flags))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(type_id == rhs.type_id))
      return false;
    return true;
  }
  bool operator != (const Counter32 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Counter32 & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Counter64 {
 public:

  static const char* ascii_fingerprint; // = "58687570D6B38392A4FABA65A8383044";
  static const uint8_t binary_fingerprint[16]; // = {0x58,0x68,0x75,0x70,0xD6,0xB3,0x83,0x92,0xA4,0xFA,0xBA,0x65,0xA8,0x38,0x30,0x44};

  Counter64() : flags(0), timestamp(0), value(0), version(1), type_id(2) {
  }

  virtual ~Counter64() throw() {}

  int32_t flags;
  int32_t timestamp;
  int64_t value;
  int8_t version;
  int8_t type_id;

  struct __isset {
    __isset() : flags(false), timestamp(false), value(false), version(false), type_id(false) {}
    bool flags;
    bool timestamp;
    bool value;
    bool version;
    bool type_id;
  } __isset;

  bool operator == (const Counter64 & rhs) const
  {
    if (!(flags == rhs.flags))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(type_id == rhs.type_id))
      return false;
    return true;
  }
  bool operator != (const Counter64 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Counter64 & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Gauge32 {
 public:

  static const char* ascii_fingerprint; // = "1584BE3F33D288DCC74EA52051285D05";
  static const uint8_t binary_fingerprint[16]; // = {0x15,0x84,0xBE,0x3F,0x33,0xD2,0x88,0xDC,0xC7,0x4E,0xA5,0x20,0x51,0x28,0x5D,0x05};

  Gauge32() : flags(0), timestamp(0), value(0), version(1), type_id(3) {
  }

  virtual ~Gauge32() throw() {}

  int32_t flags;
  int32_t timestamp;
  int32_t value;
  int8_t version;
  int8_t type_id;

  struct __isset {
    __isset() : flags(false), timestamp(false), value(false), version(false), type_id(false) {}
    bool flags;
    bool timestamp;
    bool value;
    bool version;
    bool type_id;
  } __isset;

  bool operator == (const Gauge32 & rhs) const
  {
    if (!(flags == rhs.flags))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(value == rhs.value))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(type_id == rhs.type_id))
      return false;
    return true;
  }
  bool operator != (const Gauge32 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Gauge32 & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Aggregate {
 public:

  static const char* ascii_fingerprint; // = "D87B096A4EA8A10D29B218BE651C1594";
  static const uint8_t binary_fingerprint[16]; // = {0xD8,0x7B,0x09,0x6A,0x4E,0xA8,0xA1,0x0D,0x29,0xB2,0x18,0xBE,0x65,0x1C,0x15,0x94};

  Aggregate() : flags(0), timestamp(0), average(0), delta(0), min(0), max(0), version(1), type_id(5) {
  }

  virtual ~Aggregate() throw() {}

  int32_t flags;
  int32_t timestamp;
  double average;
  double delta;
  double min;
  double max;
  int8_t version;
  int8_t type_id;

  struct __isset {
    __isset() : flags(false), timestamp(false), average(false), delta(false), min(false), max(false), version(false), type_id(false) {}
    bool flags;
    bool timestamp;
    bool average;
    bool delta;
    bool min;
    bool max;
    bool version;
    bool type_id;
  } __isset;

  bool operator == (const Aggregate & rhs) const
  {
    if (!(flags == rhs.flags))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(average == rhs.average))
      return false;
    if (!(delta == rhs.delta))
      return false;
    if (!(min == rhs.min))
      return false;
    if (!(max == rhs.max))
      return false;
    if (!(version == rhs.version))
      return false;
    if (!(type_id == rhs.type_id))
      return false;
    return true;
  }
  bool operator != (const Aggregate &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Aggregate & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class VarList {
 public:

  static const char* ascii_fingerprint; // = "F69171D27C4FA075F66E897BE869110B";
  static const uint8_t binary_fingerprint[16]; // = {0xF6,0x91,0x71,0xD2,0x7C,0x4F,0xA0,0x75,0xF6,0x6E,0x89,0x7B,0xE8,0x69,0x11,0x0B};

  VarList() {
  }

  virtual ~VarList() throw() {}

  std::vector<Counter32>  counter32;
  std::vector<Counter64>  counter64;
  std::vector<Gauge32>  gauge32;
  std::vector<Aggregate>  aggregate;

  struct __isset {
    __isset() : counter32(false), counter64(false), gauge32(false), aggregate(false) {}
    bool counter32;
    bool counter64;
    bool gauge32;
    bool aggregate;
  } __isset;

  bool operator == (const VarList & rhs) const
  {
    if (!(counter32 == rhs.counter32))
      return false;
    if (!(counter64 == rhs.counter64))
      return false;
    if (!(gauge32 == rhs.gauge32))
      return false;
    if (!(aggregate == rhs.aggregate))
      return false;
    return true;
  }
  bool operator != (const VarList &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VarList & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class SNMPPollResultPair {
 public:

  static const char* ascii_fingerprint; // = "07A9615F837F7D0A952B595DD3020972";
  static const uint8_t binary_fingerprint[16]; // = {0x07,0xA9,0x61,0x5F,0x83,0x7F,0x7D,0x0A,0x95,0x2B,0x59,0x5D,0xD3,0x02,0x09,0x72};

  SNMPPollResultPair() : OIDName(""), value("") {
  }

  virtual ~SNMPPollResultPair() throw() {}

  std::string OIDName;
  std::string value;

  struct __isset {
    __isset() : OIDName(false), value(false) {}
    bool OIDName;
    bool value;
  } __isset;

  bool operator == (const SNMPPollResultPair & rhs) const
  {
    if (!(OIDName == rhs.OIDName))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const SNMPPollResultPair &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SNMPPollResultPair & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class SNMPPollResult {
 public:

  static const char* ascii_fingerprint; // = "A120DB3C7D3315EC9ABE6E56137F87EB";
  static const uint8_t binary_fingerprint[16]; // = {0xA1,0x20,0xDB,0x3C,0x7D,0x33,0x15,0xEC,0x9A,0xBE,0x6E,0x56,0x13,0x7F,0x87,0xEB};

  SNMPPollResult() : device_id(0), oidset_id(0), timestamp(0) {
  }

  virtual ~SNMPPollResult() throw() {}

  int32_t device_id;
  int32_t oidset_id;
  int32_t timestamp;
  std::vector<std::vector<std::string> >  vars;

  struct __isset {
    __isset() : device_id(false), oidset_id(false), timestamp(false), vars(false) {}
    bool device_id;
    bool oidset_id;
    bool timestamp;
    bool vars;
  } __isset;

  bool operator == (const SNMPPollResult & rhs) const
  {
    if (!(device_id == rhs.device_id))
      return false;
    if (!(oidset_id == rhs.oidset_id))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(vars == rhs.vars))
      return false;
    return true;
  }
  bool operator != (const SNMPPollResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SNMPPollResult & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class Rate {
 public:

  static const char* ascii_fingerprint; // = "0B663F1913C9C6F43150B524A8B76386";
  static const uint8_t binary_fingerprint[16]; // = {0x0B,0x66,0x3F,0x19,0x13,0xC9,0xC6,0xF4,0x31,0x50,0xB5,0x24,0xA8,0xB7,0x63,0x86};

  Rate() : timestamp(0), rate(0) {
  }

  virtual ~Rate() throw() {}

  int32_t timestamp;
  double rate;

  struct __isset {
    __isset() : timestamp(false), rate(false) {}
    bool timestamp;
    bool rate;
  } __isset;

  bool operator == (const Rate & rhs) const
  {
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(rate == rhs.rate))
      return false;
    return true;
  }
  bool operator != (const Rate &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Rate & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

class ESDBError : public facebook::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  ESDBError() : what("") {
  }

  virtual ~ESDBError() throw() {}

  std::string what;

  struct __isset {
    __isset() : what(false) {}
    bool what;
  } __isset;

  bool operator == (const ESDBError & rhs) const
  {
    if (!(what == rhs.what))
      return false;
    return true;
  }
  bool operator != (const ESDBError &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ESDBError & ) const;

  uint32_t read(facebook::thrift::protocol::TProtocol* iprot);
  uint32_t write(facebook::thrift::protocol::TProtocol* oprot) const;

};

} // namespace

#endif
